// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzsxbbvtiovllfjlibhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6c3hiYnZ0aW92bGxmamxpYmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NzA0ODQsImV4cCI6MjA1ODQ0NjQ4NH0.bc1E3b6Zj_BqQzye9okkXDBDxv43X8elAn30Qaq2IEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);